apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: track-helm-latest-version
  namespace: argocd
spec: 
  destination:
    namespace: track-helm-latest-version
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: ingress-nginx
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: '*' # can use > or < as well, >=1.0.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true