apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: track-helm-range
  namespace: argocd
spec: 
  destination:
    namespace: track-helm-range
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: sealed-secrets
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 1.* # can use > or < as well, >=1.0.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true