apiVersion: argoproj.io/v1apha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec: 
  destionation:
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook
    repoURL: "https://github.com/Dsincennes/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true