apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    type: git
    url: https://github.com/dsincennes/argocd-example-apps-private.git
    password: password123test
    username: my-token